const quizData = {
    streams: {
      Science: [
        "Engineering",
        "Medicine",
        "Research",
        "IT & Computer Science",
        "Environmental Science",
        "Pure Sciences",
        "Aviation",
        "Defense Services",
      ],
      Arts: [
        "History",
        "Political Science",
        "Psychology",
        "Fine Arts",
        "Literature",
        "Philosophy",
        "Sociology",
        "Performing Arts",
      ],
      Commerce: [
        "Accounting",
        "Finance",
        "Management",
        "Economics",
        "Business Studies",
        "Banking & Insurance",
        "Entrepreneurship",
      ],
      Vocational: [
        "Hotel Management",
        "Event Management",
        "Travel & Tourism",
        "Culinary Arts",
        "Fashion Design",
        "Interior Design",
        "Graphic Design",
      ],
      Professional: [
        "Law",
        "Chartered Accountant",
        "Architecture",
        "Journalism",
        "Teaching",
        "Social Work",
      ],
    },
    subOptions: {
      Engineering: {
        ComputerScience: [46, 47, 48, 49],
        Mechanical: ["Automobile Engineering", "Robotics", "Thermal Engineering", "Manufacturing"],
        Civil: ["Structural Engineering", "Construction Management", "Environmental Engineering", "Geotechnical"],
        Electrical: ["Power Systems", "Control Systems", "Signal Processing", "Renewable Energy"],
        Electronics: ["Communication Systems", "Embedded Systems", "Microelectronics Engineering", "Nanotechnology"],
        Chemical: ["Biochemical Engineering", "Petrochemical Engineering", "Food Processing Engineering", "Pharmaceutical Engineering"],
        Aerospace: ["Aircraft Design", "Space Engineering", "Aerodynamics", "Avionics"],
      },
      Medicine: {
        MBBS: ["General Practitioner", "Surgeon", "Pediatrician", "Cardiologist", "Dermatologist", "Orthopedic Surgeon"],
        Pharmacy: ["Clinical Pharmacist", "Pharmaceutical Researcher", "Drug Safety Associate", "Production Manager"],
        Nursing: ["Critical Care Nurse", "Psychiatric Nurse", "Community Health Nurse", "Nurse Educator", "Oncology Nurse"],
        Physiotherapy: ["Orthopedic Physiotherapist", "Sports Physiotherapist", "Pediatric Physiotherapist", "Neurological Physiotherapist"],
        Dentistry: ["General Dentist", "Orthodontist", "Periodontist", "Oral Surgeon"],
        Veterinary: ["Animal Surgeon", "Veterinarian", "Pet Care Specialist", "Wildlife Veterinarian"],
      },
      Research: {
        Biotechnology: ["Genetic Engineering", "Bioinformatics", "Pharmaceutical Biotechnology", "Food Biotechnology"],
        Physics: ["Astrophysics", "Nuclear Physics", "Quantum Mechanics", "Material Science"],
        Chemistry: ["Analytical Chemistry", "Organic Chemistry", "Industrial Chemistry", "Pharmacology"],
        EnvironmentalStudies: ["Climate Change", "Waste Management", "Environmental Impact Assessment", "Sustainable Development"],
        Astrophysics: ["Astronomy", "Cosmology", "Planetary Science", "Space Research"],
      },
      "IT & Computer Science": {
        "Data Science": ["Machine Learning", "Big Data", "Data Analytics", "Artificial Intelligence"],
        "Cybersecurity": ["Network Security", "Cryptography", "Ethical Hacking", "Information Security"],
        "Cloud Computing": ["AWS Certified Solutions Architect", "Cloud Storage Architect", "Cloud Security Specialist", "DevOps Engineer"],
        "Web Development": ["Front-End Development", "Back-End Development", "Full Stack Development", "UI/UX Design"],
      },
      EnvironmentalScience: {
        "Sustainability Studies": ["Sustainable Development", "Environmental Consulting", "Renewable Energy", "Sustainability Management"],
        "Wildlife Conservation": ["Wildlife Biologist", "Conservationist", "Ecologist", "Field Researcher"],
        "Forestry": ["Forest Management", "Forest Ecology", "Conservation Research", "Wildlife Protection"],
      },
      PureSciences: {
        Physics: ["Particle Physics", "Quantum Mechanics", "Nuclear Physics", "Theoretical Physics"],
        Chemistry: ["Inorganic Chemistry", "Analytical Chemistry", "Biochemistry", "Physical Chemistry"],
        Mathematics: ["Pure Mathematics", "Applied Mathematics", "Statistical Research", "Operations Research"],
        Biology: ["Genetics", "Molecular Biology", "Microbiology", "Ecology"],
      },
      Aviation: {
        "Commercial Pilot": ["Pilot Training", "Aviation Safety", "Flight Operations", "Airline Pilot"],
        "Aviation Management": ["Airport Operations", "Airline Management", "Air Traffic Control", "Airport Security"],
        "Air Traffic Control": ["Radar Systems", "Navigation", "Communication Systems", "Safety Protocols"],
      },
      DefenseServices: {
        Army: ["Officer Training", "Military Intelligence", "Combat Operations", "Engineering Corps"],
        Navy: ["Naval Officer", "Submarine Operations", "Naval Engineering", "Maritime Operations"],
        AirForce: ["Pilot", "Flight Engineer", "Radar Operator", "Air Traffic Control"],
        CoastGuard: ["Marine Safety", "Rescue Operations", "Coastal Protection", "Environmental Monitoring"],
      },
      History: {
        Archaeology: ["Field Archaeologist", "Museum Curator", "Conservation Specialist", "Historical Researcher"],
        Museology: ["Museum Educator", "Collections Manager", "Exhibition Designer", "Museum Registrar"],
        Anthropology: ["Cultural Anthropologist", "Forensic Anthropologist", "Linguistic Anthropologist", "Archaeological Anthropologist"],
      },
      PoliticalScience: {
        Governance: ["Public Policy Analyst", "Government Officer", "Urban Planner", "Legislative Aide"],
        InternationalRelations: ["Diplomat", "Foreign Affairs Specialist", "International Trade Analyst", "Peacekeeper"],
        PoliticalTheory: ["Political Philosopher", "Think Tank Researcher", "Ethics Advisor", "Policy Critic"],
        ComparativePolitics: ["Area Specialist", "Election Analyst", "Political Data Scientist", "Democracy Consultant"],
        PublicAdministration: ["Civil Servant", "Policy Advisor", "Administrative Manager", "Budget Analyst"],
      },
      Psychology: {
        ClinicalPsychology: ["Clinical Psychologist", "Psychotherapist", "Neuropsychologist", "Rehabilitation Specialist"],
        CounselingPsychology: ["School Counselor", "Career Counselor","Marriage and Family Therapist", "Addiction Counselor"],
        EducationalPsychology: ["Educational Psychologist","Learning Disabilities Specialist","Academic Coach","Curriculum Developer"],
        ForensicPsychology: ["Criminal Psychologist","Jury Consultant", "Forensic Evaluator","Behavioral Analyst"],
        DevelopmentalPsychology: ["Child Psychologist","Adolescent Psychologist","Gerontologist","Research Specialist"],
        HealthPsychology: ["Health Psychologist","Behavioral Health Specialist","Wellness Consultant","Stress Management Counselor"],
      },            
      FineArts: {
        Painting: ["Oil Painting", "Watercolor Artist", "Muralist", "Digital Painter"],
        Sculpture: ["Clay Modeling", "Stone Carving", "Metal Sculpting", "3D Modeling"],
        Photography: ["Photojournalism", "Wildlife Photographer", "Fashion Photographer", "Event Photographer"],
      },
      Literature: {
        CreativeWriting: ["Novelist", "Screenwriter", "Poet", "Content Writer"],
        Journalism: ["Investigative Journalist", "Broadcast Journalist", "Photojournalist", "Editor"],
        Teaching: ["English Teacher", "Literature Professor", "Linguistics Specialist", "Creative Writing Instructor"],
      },
      Philosophy: {
        Ethics: ["Ethicist", "Corporate Ethics Advisor", "Medical Ethicist", "Philosophical Consultant"],
        Metaphysics: ["Philosophical Researcher", "Metaphysics Lecturer", "Author on Ontology", "Cultural Critic"],
        Epistemology: ["Knowledge Analyst", "Cognitive Science Researcher", "Philosophy of Science Expert", "Educational Theorist"],
        PoliticalPhilosophy: ["Social Justice Advocate", "Policy Analyst", "Human Rights Consultant", "Civic Educator"],
        Logic: ["Logician", "Mathematical Philosopher", "Computational Logic Expert", "Debate Coach"],
      },
      Sociology: {
        SocialTheory: ["Sociologist", "Cultural Critic", "Social Researcher", "Political Sociologist"],
        Criminology: ["Forensic Sociologist", "Criminal Justice Researcher", "Victimology Specialist", "Law Enforcement Analyst"],
        MedicalSociology: ["Health Policy Analyst", "Public Health Researcher", "Medical Sociologist", "Healthcare Consultant"],
        UrbanSociology: ["Urban Planner", "City Development Analyst", "Housing Policy Expert", "Community Engagement Specialist"],
        EducationSociology: ["Educational Policy Analyst", "Curriculum Developer", "Social Work Educator", "School Administrator"],
      },
      PerformingArts: {
        Theatre: ["Theater Director", "Playwright", "Stage Manager", "Actor", "Set Designer"],
        Dance: ["Choreographer", "Ballet Dancer", "Contemporary Dancer", "Dance Instructor", "Dance Critic"],
        Music: ["Composer", "Music Producer", "Sound Engineer", "Orchestra Conductor", "Music Teacher"],
        Film: ["Film Director", "Cinematographer", "Screenwriter", "Film Editor", "Actor"],
        Opera: ["Opera Singer", "Opera Director", "Opera Composer", "Voice Coach", "Orchestra Conductor"],
      },   
      Accounting: {
        CA: ["Tax Consultant", "Internal Auditor", "Finance Controller", "Chartered Accountant"],
        CMA: ["Cost Auditor", "Management Accountant", "Budget Analyst", "Cost Controller"],
        CPA: ["Public Accountant", "Auditor", "Forensic Accountant", "Tax Advisor"],
      },               
      Finance: {
        "Investment Banking": ["Equity Analyst", "Portfolio Manager", "Mergers & Acquisitions Specialist", "Risk Analyst"],
        "Economics": ["Economic Policy Advisor", "Market Research Analyst", "Economist", "Data Analyst"],
        "Stock Trading": ["Trader", "Equity Research Analyst", "Broker", "Quantitative Analyst"],
      },
      Management: {
        MBA: ["Business Analyst", "Operations Manager", "Marketing Strategist", "Project Manager"],
        HR: ["Recruitment Specialist", "HR Generalist", "Training & Development Manager", "Employee Relations Specialist"],
        Marketing: ["Digital Marketing", "Brand Management", "Market Research", "Advertising Specialist"],
      },
      Economics: {
        Microeconomics: ["Consumer Behavior Analyst", "Pricing Analyst", "Supply Chain Specialist", "Product Manager"],
        Macroeconomics: ["Economic Advisor", "Monetary Policy Analyst", "Government Economic Planner", "Economic Consultant"],
        DevelopmentEconomics: [ "Poverty Analyst", "International Aid Specialist", "Urban Development Planner", "Social Economist"],
        EnvironmentalEconomics: ["Environmental Policy Analyst", "Sustainability Consultant", "Natural Resource Economist", "Environmental Data Analyst"],
        BehavioralEconomics: ["Behavioral Scientist", "Consumer Psychologist", "Public Policy Advisor", "Market Research Analyst"],
      },
      BusinessStudies: {
        BusinessManagement: ["Business Analyst", "General Manager", "Project Manager", "Entrepreneur"],
        Marketing: ["Marketing Strategist", "Brand Manager", "Digital Marketing Specialist", "Advertising Manager"],
        HumanResources: ["HR Manager", "Recruitment Specialist", "Employee Relations Manager", "Talent Acquisition Specialist"],
        Finance: ["Financial Analyst", "Investment Banker", "Corporate Finance Specialist", "Financial Planner"],
        InternationalBusiness: ["International Trade Specialist", "Global Supply Chain Manager", "International Marketing Manager", "Global Business Consultant"],
      },            
      "Banking & Insurance": {
        "Banking Operations": ["Bank Manager", "Loan Officer", "Credit Analyst", "Risk Manager"],
        "Insurance Underwriting": ["Insurance Analyst", "Claims Adjuster", "Underwriting Assistant", "Risk Assessment Specialist"],
      },
      Entrepreneurship: {
        "Startup Management": ["Product Manager", "Business Development", "Founder", "Venture Capitalist"],
        "Innovation Management": ["Product Development", "Innovation Strategy", "Marketing Lead", "Business Analyst"],
      },
      HotelManagement: {
        "Hospitality Management": ["Hotel Manager", "Resort Manager", "Guest Relations Manager", "Food & Beverage Manager"],
        "Tourism Management": ["Travel Consultant", "Tour Guide", "Destination Marketing", "Cultural Ambassador"],
      },
      "Event Management": {
        "Wedding Planning": ["Wedding Coordinator", "Event Stylist", "Catering Manager", "Event Manager"],
        "Corporate Events": ["Event Planner", "Conference Coordinator", "Event Logistics", "Sponsorship Manager"],
      },
      TravelAndTourism: {
        HospitalityManagement: ["Hotel Manager", "Event Coordinator", "Guest Relations Manager", "Restaurant Manager"],
        TourOperations: ["Tour Operator", "Tour Guide", "Travel Consultant", "Itinerary Planner"],
        TravelMarketing: ["Travel Marketing Manager", "Social Media Manager (Tourism)", "Destination Marketing Specialist", "Content Creator (Tourism)"],
        Aviation: ["Pilot", "Airline Cabin Crew", "Aviation Safety Officer", "Airport Manager"],
        SustainableTourism: ["Eco-Tourism Guide", "Sustainability Consultant", "Sustainable Tourism Planner", "Environmental Impact Analyst"],
      },      
      "Culinary Arts": {
        "Culinary Arts": ["Head Chef", "Pastry Chef", "Restaurant Manager", "Culinary Instructor"],
        "Baking & Patisserie": ["Pastry Chef", "Baker", "Cake Designer", "Confectioner"],
      },
      "Fashion Design": {
        "Fashion Design": ["Fashion Designer", "Textile Designer", "Fashion Merchandiser", "Fashion Stylist"],
        "Accessory Design": ["Jewelry Designer", "Footwear Designer", "Bag Designer", "Accessory Stylist"],
      },
      "Interior Design": {
        "Interior Design": ["Residential Design", "Commercial Design", "Furniture Design", "Sustainable Design"],
        "Architecture": ["Building Design", "Urban Design", "Landscape Architecture", "Interior Architecture"],
      },
      "Graphic Design": {
        "UI/UX Design": ["UX Designer", "UI Designer", "Interaction Designer", "Prototyping Specialist"],
        "Visual Communication": ["Graphic Designer", "Brand Designer", "Illustrator", "Motion Graphics Designer"],
      },
      Law: {
        "Corporate Law": ["Mergers & Acquisitions", "Intellectual Property Law", "Contract Law", "Legal Advisor"],
        "Criminal Law": ["Criminal Defense Lawyer", "Prosecutor", "Law Enforcement", "Forensic Expert"],
        "Family Law": ["Divorce Lawyer", "Child Custody Lawyer", "Family Mediator", "Adoption Lawyer"],
      },
      CharteredAccountant: {
        Taxation: ["Tax Consultant", "Tax Manager", "Indirect Tax Specialist", "Corporate Tax Advisor"],
        Auditing: ["Internal Auditor", "External Auditor", "Forensic Auditor", "Audit Manager"],
        FinancialManagement: ["Financial Analyst", "Risk Management Consultant", "Investment Analyst", "Financial Planner"],
        Accounting: ["General Accountant", "Management Accountant", "Cost Accountant", "Budget Analyst"],
        CorporateFinance: [ "Investment Banker", "Corporate Restructuring Consultant", "Financial Advisor", "Capital Markets Specialist"],
      },    
      Architecture: {
      UrbanDesign: ["Urban Planner", "City Architect", "Landscape Architect", "Infrastructure Planner"],
      ResidentialArchitecture: ["Residential Architect", "Interior Designer", "Home Renovation Specialist", "Building Inspector"],
      CommercialArchitecture: ["Commercial Space Designer", "Office Architect", "Retail Space Planner", "Building Project Manager"],
      EnvironmentalArchitecture: ["Sustainable Architect", "Green Building Consultant", "Energy Efficiency Expert", "Eco-Friendly Building Designer"],
      HistoricPreservation: ["Conservation Architect", "Heritage Site Manager", "Restoration Specialist", "Cultural Heritage Consultant"],
      },  
      Journalism: {
        "Broadcast Journalism": ["News Anchor", "Radio Jockey", "Television Reporter", "Field Correspondent"],
        "Investigative Journalism": ["Reporter", "Documentary Filmmaker", "Research Journalist", "Editor"],
      },
      Teaching: {
        "Primary Education": ["Class Teacher", "School Administrator", "Counselor", "Special Education Teacher"],
        "Higher Education": ["Professor", "Lecturer", "Researcher", "Academic Coordinator"],
      },
      "Social Work": {
        "Community Development": ["Social Worker", "NGO Consultant", "Community Outreach Coordinator", "Public Policy Expert"],
        "Child Welfare": ["Child Protection Officer", "Social Service Worker", "Therapist", "Counselor"],
      },
    },
  };

  export default quizData;